In [10]:
import pandas as pd
import geopandas as gpd
cctv = pd.read_excel('중구_CCTV.xlsx')
node = pd.read_excel('중구_노드_링크_네트워크데이터.xlsx')

In [11]:
cctv.head()

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,WGS84위도,WGS84경도
0,서울특별시 중구청,서울특별시 중구 수표로 45,서울특별시 중구 저동2가 78,생활방범,37.5654,126.9891
1,서울특별시 중구청,서울특별시 중구 남대문로1길 16 (북창동),서울특별시 중구 북창동 118,생활방범,37.5618,126.9775
2,서울특별시 중구청,서울특별시 중구 을지로 35 (을지로1가),서울특별시 중구 을지로1가 101-1,생활방범,37.5667,126.9816
3,서울특별시 중구청,서울특별시 중구 소공로 109 (소공동),서울특별시 중구 소공동 110-1,생활방범,37.5639,126.9779
4,서울특별시 중구청,서울특별시 중구 다동길 43 (다동),서울특별시 중구 다동 70,생활방범,37.5680,126.9814

In [12]:
node.head()

,Unnamed: 0,노드링크 유형,노드 WKT,노드 ID,노드 유형 코드,링크 WKT,링크 ID,링크 유형 코드,시작노드 ID,종료노드 ID,...,읍면동명,고가도로,지하철네트워크,교량,터널,육교,횡단보도,"공원,녹지",건물내,행정동코드
0,0,NODE,POINT(127.00138520146373 37.568187437157185),66847,0.0,NaN,0,NaN,NaN,NaN,...,주교동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140605
1,1,NODE,POINT(127.01697814071575 37.56762896761354),127069,0.0,NaN,0,NaN,NaN,NaN,...,흥인동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615
2,2,NODE,POINT(127.02195932653572 37.56805381260861),9440,0.0,NaN,0,NaN,NaN,NaN,...,황학동,NaN,NaN,NaN,NaN,0,1,NaN,NaN,11140670
3,3,NODE,POINT(126.97646615812025 37.55427380378025),10380,0.0,NaN,0,NaN,NaN,NaN,...,남대문로5가,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140540
4,4,NODE,POINT(127.01917432263897 37.56617541509709),9255,0.0,NaN,0,NaN,NaN,NaN,...,황학동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140670

In [13]:
### 노드데이터 좌표계설정

node = node[(node['노드링크 유형'] == 'NODE') &
        (node['육교'] == 0) &
        (node['횡단보도'] == 0)]

def multipolygon_to_coordinates(x):
    lon, lat = x[0].exterior.xy
    return [[x, y] for x, y in zip(lon, lat)]

## 다각형에서 평행좌표
def polygon_to_coordinates(x):
    lon, lat = x.exterior.xy
    return [[x, y] for x, y in zip(lon, lat)]

## 지리데이터프레임으로 변환

import geopandas as gpd
gs = gpd.GeoSeries.from_wkt(node['노드 WKT'])
## 좌표계 설정하는 거 같음
# df_dobo_100 = gpd.GeoDataFrame(df, geometry = gs, crs = 'epsg:4326')
node_gs = gpd.GeoDataFrame(node, geometry = gs, crs = 'epsg:4326')
node_gs.head()

,Unnamed: 0,노드링크 유형,노드 WKT,노드 ID,노드 유형 코드,링크 WKT,링크 ID,링크 유형 코드,시작노드 ID,종료노드 ID,...,고가도로,지하철네트워크,교량,터널,육교,횡단보도,"공원,녹지",건물내,행정동코드,geometry
0,0,NODE,POINT(127.00138520146373 37.568187437157185),66847,0.0,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140605,POINT (127.00139 37.56819)
1,1,NODE,POINT(127.01697814071575 37.56762896761354),127069,0.0,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615,POINT (127.01698 37.56763)
3,3,NODE,POINT(126.97646615812025 37.55427380378025),10380,0.0,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140540,POINT (126.97647 37.55427)
4,4,NODE,POINT(127.01917432263897 37.56617541509709),9255,0.0,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140670,POINT (127.01917 37.56618)
5,5,NODE,POINT(126.96329524184776 37.55797263212856),9627,0.0,NaN,0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140680,POINT (126.96330 37.55797)

In [14]:
# POINT(127.00138520146373 )

In [15]:
# node_gs = gpd.GeoDataFrame(node, geometry = gs, crs = 'epsg:4326')
# node_gs.head()

In [16]:
## CCTV 데이터 지리데이터로 ㄱㄱ 

cctv = gpd.GeoDataFrame(cctv,geometry=gpd.points_from_xy(cctv['WGS84경도'],cctv['WGS84위도']),crs = 'epsg:4326')
cctv.head()

,관리기관명,소재지도로명주소,소재지지번주소,설치목적구분,WGS84위도,WGS84경도,geometry
0,서울특별시 중구청,서울특별시 중구 수표로 45,서울특별시 중구 저동2가 78,생활방범,37.5654,126.9891,POINT (126.98910 37.56540)
1,서울특별시 중구청,서울특별시 중구 남대문로1길 16 (북창동),서울특별시 중구 북창동 118,생활방범,37.5618,126.9775,POINT (126.97750 37.56180)
2,서울특별시 중구청,서울특별시 중구 을지로 35 (을지로1가),서울특별시 중구 을지로1가 101-1,생활방범,37.5667,126.9816,POINT (126.98160 37.56670)
3,서울특별시 중구청,서울특별시 중구 소공로 109 (소공동),서울특별시 중구 소공동 110-1,생활방범,37.5639,126.9779,POINT (126.97790 37.56390)
4,서울특별시 중구청,서울특별시 중구 다동길 43 (다동),서울특별시 중구 다동 70,생활방범,37.5680,126.9814,POINT (126.98140 37.56800)

In [19]:
import math
cctv_locations = [(37.5654, 126.9891), (37.5618, 126.9775), (37.5667, 126.9816)]
center = (127.00138520146373,37.568187437157185)
radius = 1

def count_cctv_within_radius(cctv_locations, center, radius):
    count = 0
    for cctv in cctv_locations:
        x, y = cctv
        distance = math.sqrt((x - center[0])**2 + (y - center[1])**2)
        if distance <= radius:
            count += 1
    return count
cctv_count = count_cctv_within_radius(cctv_locations, center, radius)
print(f"반경 {radius} 내에 있는 CCTV 개수: {cctv_count} 개")

반경 1 내에 있는 CCTV 개수: 0 개

In [9]:
import geopandas as gpd
from shapely.geometry import Point

In [23]:
## 중심좌표는 각 노드 좌표
center_point = node_gs.loc[10,'geometry']
# 좌표 시스템을 변경하여 미터 단위로 변환
# center_point = center_point.to_crs('EPSG:3395')  # EPSG:3395는 웹 메르카토르 좌표 시스템이고, 미터 단위입니다.
radius_meter = 50

In [24]:
cctv_point = cctv['geometry']

In [25]:

# 반경 내에 있는 CCTV 필터링
cctv_within_radius = cctv[cctv['geometry'].distance(center_point) <= radius_meter]
cctv_count = len(cctv_within_radius)
print(f"반경 {radius_meter} 미터 내에 있는 CCTV 개수: {cctv_count} 개")

반경 50 미터 내에 있는 CCTV 개수: 1026 개

C:\Users\Hamin\AppData\Local\Temp\ipykernel_12008\1990437189.py:2: UserWarning: Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  cctv_within_radius = cctv[cctv['geometry'].distance(center_point) <= radius_meter]

In [16]:
cctv_within_radius = node_gs.loc[node_gs['geometry'].distance(cctv_point) <= radius_meter,:]
cctv_count = len(cctv_within_radius)
print(f"반경 {radius_meter} 미터 내에 있는 CCTV 개수: {cctv_count} 개")

반경 50 미터 내에 있는 CCTV 개수: 550 개

C:\Users\Hamin\AppData\Local\Temp\ipykernel_11984\546588565.py:1: UserWarning: The indices of the two GeoSeries are different.
  cctv_within_radius = node_gs.loc[node_gs['geometry'].distance(cctv_point) <= radius_meter,:]
C:\Users\Hamin\AppData\Local\Temp\ipykernel_11984\546588565.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'distance' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  cctv_within_radius = node_gs.loc[node_gs['geometry'].distance(cctv_point) <= radius_meter,:]