In [78]:
import pandas as pd

In [79]:
hmotel = pd.read_excel('숙박업소_현황.xlsx')
hmotel.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y)
0,0,0,0,3010000,3010000-214-2021-00001,영업/정상,영업,1350.84,서울특별시 중구 인현동1가 158,"서울특별시 중구 충무로 24, 3~17층 (인현동1가)",어반스테이 명동,숙박업(생활),199345.466097,451233.369781
1,1,1,1,3010000,3010000-201-2019-00008,영업/정상,영업,610.66,서울특별시 중구 남산동2가 35-2,"서울특별시 중구 퇴계로18길 43, 지층, 1~2층 (남산동2가)",오요5(oYo5),관광호텔,198591.133748,450740.353160
2,2,2,2,3010000,3010000-214-2023-00002,영업/정상,영업,2808.85,서울특별시 중구 남대문로3가 94,서울특별시 중구 남대문로 27 (남대문로3가),더스테이클래식호텔,숙박업(생활),198037.338494,451010.546630
3,3,3,3,3010000,3010000-201-2017-00010,영업/정상,영업,178.54,서울특별시 중구 남산동2가 33-3 1~2층,"서울특별시 중구 퇴계로18길 41 (남산동2가, 1~2층)",오요5롯지A(oYo5LodgeA),숙박업 기타,198602.119250,450758.364667
4,4,4,4,3010000,3010000-201-2017-00011,영업/정상,영업,166.54,"서울특별시 중구 남산동2가 33 1,2층","서울특별시 중구 퇴계로18길 37 (남산동2가, 1,2층)",오요5롯지B(oYo5LodgeB),관광호텔,198607.670947,450770.829936

In [80]:
hmotel[['시','구','동','상세주소2']] = hmotel['지번주소'].str.split(" ",n=3,expand=True)

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),시,구,동,상세주소2
0,0,0,0,3010000,3010000-214-2021-00001,영업/정상,영업,1350.84,서울특별시 중구 인현동1가 158,"서울특별시 중구 충무로 24, 3~17층 (인현동1가)",어반스테이 명동,숙박업(생활),199345.466097,451233.369781,서울특별시,중구,인현동1가,158
1,1,1,1,3010000,3010000-201-2019-00008,영업/정상,영업,610.66,서울특별시 중구 남산동2가 35-2,"서울특별시 중구 퇴계로18길 43, 지층, 1~2층 (남산동2가)",오요5(oYo5),관광호텔,198591.133748,450740.353160,서울특별시,중구,남산동2가,35-2
2,2,2,2,3010000,3010000-214-2023-00002,영업/정상,영업,2808.85,서울특별시 중구 남대문로3가 94,서울특별시 중구 남대문로 27 (남대문로3가),더스테이클래식호텔,숙박업(생활),198037.338494,451010.546630,서울특별시,중구,남대문로3가,94
3,3,3,3,3010000,3010000-201-2017-00010,영업/정상,영업,178.54,서울특별시 중구 남산동2가 33-3 1~2층,"서울특별시 중구 퇴계로18길 41 (남산동2가, 1~2층)",오요5롯지A(oYo5LodgeA),숙박업 기타,198602.119250,450758.364667,서울특별시,중구,남산동2가,33-3 1~2층
4,4,4,4,3010000,3010000-201-2017-00011,영업/정상,영업,166.54,"서울특별시 중구 남산동2가 33 1,2층","서울특별시 중구 퇴계로18길 37 (남산동2가, 1,2층)",오요5롯지B(oYo5LodgeB),관광호텔,198607.670947,450770.829936,서울특별시,중구,남산동2가,"33 1,2층"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5947,5947,5947,6671,3000000,3000000-201-1976-00193,영업/정상,영업,371.58,서울특별시 종로구 종로5가 66-1,서울특별시 종로구 대학로2길 12 (종로5가),이녹(李綠),여관업,200161.563979,452132.172041,서울특별시,종로구,종로5가,66-1
5948,5948,5948,6672,3150000,3150000-201-1997-00014,영업/정상,영업,624.21,서울특별시 강서구 화곡동 24-77,서울특별시 강서구 화곡로42길 17 (화곡동),설레임모텔,여관업,186372.412823,449366.415349,서울특별시,강서구,화곡동,24-77
5949,5949,5949,6673,3190000,3190000-201-1991-00086,영업/정상,영업,450.25,서울특별시 동작구 신대방동 687-8,서울특별시 동작구 신대방3길 59 (신대방동),신라장,여관업,191832.871758,442881.349005,서울특별시,동작구,신대방동,687-8
5950,5950,5950,6674,3070000,3070000-201-2002-00006,영업/정상,영업,372.93,서울특별시 성북구 정릉동 408-11,서울특별시 성북구 보국문로 27 (정릉동),웨이브,여관업,200850.193897,456070.122190,서울특별시,성북구,정릉동,408-11
5951,5951,5951,6675,3220000,3220000-201-2005-00001,영업/정상,영업,"15,155.68",서울특별시 강남구 대치동 995-14 지상3층~21.23층,"서울특별시 강남구 테헤란로 606 (대치동,지상3층~21.23층)",파크하얏트서울,관광호텔,205601.904042,445151.509505,서울특별시,강남구,대치동,995-14 지상3층~21.23층

In [82]:
hmotel.drop('상세주소2',axis=1,inplace=True)

In [83]:
hmotel.head()

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),시,구,동
0,0,0,0,3010000,3010000-214-2021-00001,영업/정상,영업,1350.84,서울특별시 중구 인현동1가 158,"서울특별시 중구 충무로 24, 3~17층 (인현동1가)",어반스테이 명동,숙박업(생활),199345.466097,451233.369781,서울특별시,중구,인현동1가
1,1,1,1,3010000,3010000-201-2019-00008,영업/정상,영업,610.66,서울특별시 중구 남산동2가 35-2,"서울특별시 중구 퇴계로18길 43, 지층, 1~2층 (남산동2가)",오요5(oYo5),관광호텔,198591.133748,450740.353160,서울특별시,중구,남산동2가
2,2,2,2,3010000,3010000-214-2023-00002,영업/정상,영업,2808.85,서울특별시 중구 남대문로3가 94,서울특별시 중구 남대문로 27 (남대문로3가),더스테이클래식호텔,숙박업(생활),198037.338494,451010.546630,서울특별시,중구,남대문로3가
3,3,3,3,3010000,3010000-201-2017-00010,영업/정상,영업,178.54,서울특별시 중구 남산동2가 33-3 1~2층,"서울특별시 중구 퇴계로18길 41 (남산동2가, 1~2층)",오요5롯지A(oYo5LodgeA),숙박업 기타,198602.119250,450758.364667,서울특별시,중구,남산동2가
4,4,4,4,3010000,3010000-201-2017-00011,영업/정상,영업,166.54,"서울특별시 중구 남산동2가 33 1,2층","서울특별시 중구 퇴계로18길 37 (남산동2가, 1,2층)",오요5롯지B(oYo5LodgeB),관광호텔,198607.670947,450770.829936,서울특별시,중구,남산동2가

In [86]:
hmotel.isnull().sum()

Unnamed: 0.2       0
Unnamed: 0.1       0
Unnamed: 0         0
개방자치단체코드           0
관리번호               0
영업상태명              0
상세영업상태명            0
소재지면적              5
지번주소              11
도로명주소           1961
사업장명               0
업태구분명              0
좌표정보(X)            0
좌표정보(Y)            0
시                 11
구                 11
동                 11
dtype: int64

In [88]:
hmotel.loc[hmotel['지번주소'].isnull(),"도로명주소"]

74                   서울특별시 영등포구 영중로4길 15-7 (영등포동3가)
169                   서울특별시 영등포구 영신로34길 33 (영등포동4가)
229                      서울특별시 종로구 종로 294, 4층 (창신동)
275                       서울특별시 종로구 수표로18길 26 (관수동)
395     서울특별시 구로구 디지털로 300 (구로동, (주)호텔롯데 롯데시티호텔 구로)
637                         서울특별시 종로구 율곡로 179 (원남동)
647                        서울특별시 종로구 율곡로6길 19 (운니동)
830                     서울특별시 종로구 창경궁로16가길 30 (연지동)
4210                     서울특별시 영등포구 선유로 100 (양평동1가)
4235                서울특별시 영등포구 영등포로 264-11 (영등포동3가)
4577                   서울특별시 영등포구 양평로28길 11 (양평동6가)
Name: 도로명주소, dtype: object

In [90]:
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영중로4길 15-7 (영등포동3가)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영중로4길 15-7 (영등포동3가)','구'] = '영등포구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영중로4길 15-7 (영등포동3가)','동'] = '영등포동3가'

hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영신로34길 33 (영등포동4가)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영신로34길 33 (영등포동4가)','구'] = '영등포구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영신로34길 33 (영등포동4가)','동'] = '영등포동4가'

hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 종로 294, 4층 (창신동)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 종로 294, 4층 (창신동)','구'] = '종로구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 종로 294, 4층 (창신동)','동'] = '창신동'

hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 수표로18길 26 (관수동)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 수표로18길 26 (관수동)','구'] = '종로구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 수표로18길 26 (관수동)','동'] = '관수동'

hmotel.loc[hmotel['도로명주소']=='서울특별시 구로구 디지털로 300 (구로동, (주)호텔롯데 롯데시티호텔 구로)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 구로구 디지털로 300 (구로동, (주)호텔롯데 롯데시티호텔 구로)','구'] = '구로구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 구로구 디지털로 300 (구로동, (주)호텔롯데 롯데시티호텔 구로)','동'] = '구로동'

hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 율곡로 179 (원남동)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 율곡로 179 (원남동)','구'] = '종로구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 율곡로 179 (원남동)','동'] = '원남동'

hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 율곡로6길 19 (운니동)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 율곡로6길 19 (운니동)','구'] = '종로구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 율곡로6길 19 (운니동)','동'] = '운니동'

hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 창경궁로16가길 30 (연지동)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 창경궁로16가길 30 (연지동)','구'] = '종로구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 종로구 창경궁로16가길 30 (연지동)','동'] = '연지동'

hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 선유로 100 (양평동1가)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 선유로 100 (양평동1가)','구'] = '영등포구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 선유로 100 (양평동1가)','동'] = '양평동1가'

hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영등포로 264-11 (영등포동3가)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영등포로 264-11 (영등포동3가)','구'] = '영등포구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 영등포로 264-11 (영등포동3가)','동'] = '영등포동3가'

hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 양평로28길 11 (양평동6가)','시'] = '서울특별시'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 양평로28길 11 (양평동6가)','구'] = '영등포구'
hmotel.loc[hmotel['도로명주소']=='서울특별시 영등포구 양평로28길 11 (양평동6가)','동'] = '양평동6가'

In [91]:
hmotel.isnull().sum()

Unnamed: 0.2       0
Unnamed: 0.1       0
Unnamed: 0         0
개방자치단체코드           0
관리번호               0
영업상태명              0
상세영업상태명            0
소재지면적              5
지번주소              11
도로명주소           1961
사업장명               0
업태구분명              0
좌표정보(X)            0
좌표정보(Y)            0
시                  0
구                  0
동                  0
dtype: int64

In [92]:
hmotel.to_excel('숙박업소_현황.xlsx')

In [93]:
test=hmotel.groupby(['구']).count()

In [94]:
test['숙박업소개수']=test['Unnamed: 0']
숙박업소_구단위_현황 = test.iloc[:-1,[-1]]
숙박업소_구단위_현황

      숙박업소개수
구
강남구      324
강동구      240
강북구      288
강서구      264
관악구      414
광진구      170
구로구      238
금천구      151
노원구       49
도봉구       61
동대문구     320
동작구      124
마포구      184
서대문구     205
서초구      123
성동구      252
성북구      261
송파구      195
양천구       49
영등포구     429
용산구      312
은평구      155
종로구      472
중구       480
중랑구      191

In [95]:

숙박업소_구단위_현황.to_excel('숙박업소_구단위_현황.xlsx')

In [96]:
숙박업소_구단위_현황

      숙박업소개수
구
강남구      324
강동구      240
강북구      288
강서구      264
관악구      414
광진구      170
구로구      238
금천구      151
노원구       49
도봉구       61
동대문구     320
동작구      124
마포구      184
서대문구     205
서초구      123
성동구      252
성북구      261
송파구      195
양천구       49
영등포구     429
용산구      312
은평구      155
종로구      472
중구       480
중랑구      191