In [1]:
import pandas as pd

In [2]:
bad = pd.read_excel('유흥업소_현황.xlsx')
bad.head()

,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),시,구,상세주소
0,0,3220000,3220000-102-2018-00006,영업/정상,영업,311.39,"서울특별시 강남구 역삼동 678-24 늘봄빌딩 2,3층","서울특별시 강남구 테헤란로27길 8-4, 늘봄빌딩 (2,3층) (역삼동)",스크린노래,룸살롱,203330.125000,444424.745000,서울특별시,강남구,"테헤란로27길 8-4, 늘봄빌딩 (2,3층) (역삼동)"
1,1,3230000,3230000-102-2017-00004,영업/정상,영업,85.41,서울특별시 송파구 가락동 98-7,"서울특별시 송파구 송파대로28길 13, 지하1층 101호 (가락동, 거북이빌딩)",골드1,룸살롱,210491.321884,443569.763243,서울특별시,송파구,"송파대로28길 13, 지하1층 101호 (가락동, 거북이빌딩)"
2,3,3180000,3180000-102-2001-14135,영업/정상,영업,83.18,서울특별시 영등포구 신길동 449-22 신성빌딩,"서울특별시 영등포구 영등포로 400, 신성빌딩 지하1층 (신길동)",린스,룸살롱,193084.355458,445642.841120,서울특별시,영등포구,"영등포로 400, 신성빌딩 지하1층 (신길동)"
3,4,3210000,3210000-102-1982-06377,영업/정상,영업,126.00,서울특별시 서초구 잠원동 12-21,서울특별시 서초구 강남대로 615 (잠원동),만남,룸살롱,201601.185141,446044.757176,서울특별시,서초구,강남대로 615 (잠원동)
4,5,3190000,3190000-102-1978-01868,폐업,폐업,98.00,서울특별시 동작구 신대방동 607-28,"서울특별시 동작구 시흥대로 646, 지하1층 (신대방동)",수,스텐드바,191742.193945,443042.735398,서울특별시,동작구,"시흥대로 646, 지하1층 (신대방동)"

In [3]:
len(bad.loc[bad['지번주소'].isnull(),:])

2

In [4]:
bad.loc[bad['지번주소'].isnull(),:]

,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),시,구,상세주소
1388,1531,3050000,3050000-102-2017-00001,폐업,폐업,99.16,NaN,"서울특별시 동대문구 장한로22길 8, 지하1층 (장안동)",프리존,룸살롱,206166.994766,451914.779527,서울특별시,동대문구,"장한로22길 8, 지하1층 (장안동)"
1456,1601,3050000,3050000-102-2017-00002,영업/정상,영업,398.00,NaN,"서울특별시 동대문구 장한로21길 8, 지하1층 (장안동)",피아노,룸살롱,206091.537163,451990.224278,서울특별시,동대문구,"장한로21길 8, 지하1층 (장안동)"

In [5]:
bad.isnull().sum()

Unnamed: 0       0
개방자치단체코드         0
관리번호             0
영업상태명            0
상세영업상태명          0
소재지면적          298
지번주소             2
도로명주소         1853
사업장명             0
업태구분명            0
좌표정보(X)          0
좌표정보(Y)          0
시             1853
구             1853
상세주소          1853
dtype: int64

In [6]:
for i,v in enumerate(bad.loc[bad['도로명주소'].isnull(),'지번주소'].str.split(' ')) :
    bad.loc[bad['도로명주소'].isnull(),'시'] = v[0]
    bad.loc[bad['도로명주소'].isnull(),'구'] = v[1]
    bad.loc[bad['도로명주소'].isnull(),'상세주소'] = v[2]
    # print(v[2])


bad.loc[bad['도로명주소'].isnull(),:]

,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),시,구,상세주소
13,14,3220000,3220000-102-2001-23094,폐업,폐업,221.88,서울특별시 강남구 논현동 164-0번지 지상3?,NaN,준,룸살롱,201962.838798,445158.311973,서울특별시,강동구,길동
21,22,3180000,3180000-102-2008-00010,영업/정상,영업,96.42,서울특별시 영등포구 영등포동3가 23-8,NaN,브이아이피(VIP),룸살롱,191900.889668,446178.426312,서울특별시,강동구,길동
83,84,3000000,3000000-102-1984-08255,폐업,폐업,NaN,서울특별시 종로구 숭인동 1252-0번지,NaN,나폴리,스텐드바,201915.038000,452657.129667,서울특별시,강동구,길동
146,147,3180000,3180000-102-2002-00013,폐업,폐업,89.53,서울특별시 영등포구 영등포동3가 17-12,NaN,백송,기타,191694.404291,446268.851590,서울특별시,강동구,길동
148,149,3000000,3000000-102-2002-00028,폐업,폐업,NaN,서울특별시 종로구 당주동 2-3번지,NaN,빠담빠담,기타,197664.940559,452234.488159,서울특별시,강동구,길동
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4634,4883,3240000,3240000-102-2001-12805,폐업,폐업,122.31,서울특별시 강동구 길동 412-14번지,NaN,씨에프유흥주점,룸살롱,212205.787403,448264.640144,서울특별시,강동구,길동
4637,4886,3240000,3240000-102-2001-12908,폐업,폐업,195.64,서울특별시 강동구 길동 446-2번지,NaN,VIP노래주점,룸살롱,211963.787409,448212.012861,서울특별시,강동구,길동
4638,4887,3240000,3240000-102-2002-13197,폐업,폐업,86.94,서울특별시 강동구 길동 457-1번지,NaN,신화,룸살롱,212062.685874,448097.972840,서울특별시,강동구,길동
4639,4888,3240000,3240000-102-1985-05533,폐업,폐업,733.78,서울특별시 강동구 천호동 454-15번지,NaN,샴푸나이트,카바레,211096.952458,448450.575808,서울특별시,강동구,길동
4640,4889,3240000,3240000-102-1987-05564,폐업,폐업,828.84,서울특별시 강동구 길동 459-2번지,NaN,연예인째즈크럽,스텐드바,212111.336831,448059.842031,서울특별시,강동구,길동

In [7]:
bad['구'].unique()

array(['강남구', '송파구', '영등포구', '서초구', '동작구', '동대문구', '종로구', '강북구', '관악구',
       '강동구', '구로구', '양천구', '은평구', '강서구', '금천구', '중랑구', '노원구', '광진구',
       '중구', '도봉구', '마포구', '성동구', '서대문구', '용산구', '성북구'], dtype=object)

In [8]:
test = bad.groupby(['구']).count()
test

,Unnamed: 0,개방자치단체코드,관리번호,영업상태명,상세영업상태명,소재지면적,지번주소,도로명주소,사업장명,업태구분명,좌표정보(X),좌표정보(Y),시,상세주소
구,,,,,,,,,,,,,,
강남구,408,408,408,408,408,408,408,408,408,408,408,408,408,408
강동구,2014,2014,2014,2014,2014,1844,2014,161,2014,2014,2014,2014,2014,2014
강북구,102,102,102,102,102,102,102,102,102,102,102,102,102,102
강서구,173,173,173,173,173,173,173,173,173,173,173,173,173,173
관악구,266,266,266,266,266,266,266,266,266,266,266,266,266,266
광진구,19,19,19,19,19,18,19,19,19,19,19,19,19,19
구로구,46,46,46,46,46,46,46,46,46,46,46,46,46,46
금천구,65,65,65,65,65,65,65,65,65,65,65,65,65,65
노원구,31,31,31,31,31,31,31,31,31,31,31,31,31,31
도봉구,26,26,26,26,26,26,26,26,26,26,26,26,26,26
동대문구,106,106,106,106,106,106,104,106,106,106,106,106,106,106
동작구,61,61,61,61,61,61,61,61,61,61,61,61,61,61
마포구,79,79,79,79,79,79,79,79,79,79,79,79,79,79
서대문구,46,46,46,46,46,46,46,46,46,46,46,46,46,46
서초구,100,100,100,100,100,100,100,100,100,100,100,100,100,100
성동구,26,26,26,26,26,26,26,26,26,26,26,26,26,26
성북구,9,9,9,9,9,9,9,9,9,9,9,9,9,9
송파구,132,132,132,132,132,132,132,132,132,132,132,132,132,132
양천구,7,7,7,7,7,7,7,7,7,7,7,7,7,7
영등포구,238,238,238,238,238,235,238,238,238,238,238,238,238,238
용산구,37,37,37,37,37,37,37,37,37,37,37,37,37,37
은평구,104,104,104,104,104,104,104,104,104,104,104,104,104,104
종로구,245,245,245,245,245,121,245,245,245,245,245,245,245,245
중구,292,292,292,292,292,292,292,292,292,292,292,292,292,292
중랑구,30,30,30,30,30,30,30,30,30,30,30,30,30,30

In [12]:
test['유흥업소개수']=test['Unnamed: 0']
유흥업소_구단위_현황 = test.iloc[:,[-1]]
유흥업소_구단위_현황

      유흥업소개수
구
강남구      408
강동구     2014
강북구      102
강서구      173
관악구      266
광진구       19
구로구       46
금천구       65
노원구       31
도봉구       26
동대문구     106
동작구       61
마포구       79
서대문구      46
서초구      100
성동구       26
성북구        9
송파구      132
양천구        7
영등포구     238
용산구       37
은평구      104
종로구      245
중구       292
중랑구       30

In [14]:
bad.isnull().sum()

Unnamed: 0       0
개방자치단체코드         0
관리번호             0
영업상태명            0
상세영업상태명          0
소재지면적          298
지번주소             2
도로명주소         1853
사업장명             0
업태구분명            0
좌표정보(X)          0
좌표정보(Y)          0
시                0
구                0
상세주소             0
dtype: int64

In [13]:

유흥업소_구단위_현황.to_excel('유흥업소_구단위_현황.xlsx')
#

In [11]:
# 숙박업소_구단위_현황