In [1]:
import pandas as pd

In [2]:
node = pd.read_excel('중구_노드_링크_네트워크데이터.xlsx')

In [4]:

node = node[(node['노드링크 유형'] == 'NODE') &
        (node['육교'] == 0) &
        (node['횡단보도'] == 0)]

In [5]:
node

,Unnamed: 0,노드링크 유형,노드 WKT,노드 ID,노드 유형 코드,링크 WKT,링크 ID,링크 유형 코드,시작노드 ID,종료노드 ID,...,읍면동명,고가도로,지하철네트워크,교량,터널,육교,횡단보도,"공원,녹지",건물내,행정동코드
0,0,NODE,POINT(127.00138520146373 37.568187437157185),66847,0.0,NaN,0,NaN,NaN,NaN,...,주교동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140605
1,1,NODE,POINT(127.01697814071575 37.56762896761354),127069,0.0,NaN,0,NaN,NaN,NaN,...,흥인동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615
3,3,NODE,POINT(126.97646615812025 37.55427380378025),10380,0.0,NaN,0,NaN,NaN,NaN,...,남대문로5가,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140540
4,4,NODE,POINT(127.01917432263897 37.56617541509709),9255,0.0,NaN,0,NaN,NaN,NaN,...,황학동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140670
5,5,NODE,POINT(126.96329524184776 37.55797263212856),9627,0.0,NaN,0,NaN,NaN,NaN,...,중림동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12829,12864,NODE,POINT(127.00671304470401 37.555271976044445),73931,0.0,NaN,0,NaN,NaN,NaN,...,신당동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615
12831,12866,NODE,POINT(127.00609787656336 37.555217084599064),73930,0.0,NaN,0,NaN,NaN,NaN,...,신당동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615
12833,12868,NODE,POINT(127.00662680680709 37.555271980916025),73929,0.0,NaN,0,NaN,NaN,NaN,...,신당동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615
12835,12870,NODE,POINT(127.006744648147 37.55508202591123),73928,0.0,NaN,0,NaN,NaN,NaN,...,신당동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615
12837,12872,NODE,POINT(127.0068510192633 37.555205600630416),73927,0.0,NaN,0,NaN,NaN,NaN,...,신당동,NaN,NaN,NaN,NaN,0,0,NaN,NaN,11140615

In [6]:
node.to_csv('설치불가능_제외.csv')